---
apiVersion: v1
kind: Namespace
metadata: 
   name: notejam

---
apiVersion: v1
kind: Service
metadata:
   name: notejam
   namespace: notejam
spec:
   selector:
       app: notejam
   type: NodePort

   ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notejam
  namespace: notejam
spec:
  replicas: 4
  selector:
    matchLabels:
         app: notejam
  template:
    metadata:
      labels:
        app: notejam
    spec:
      containers:
      - name: notejam
        image: soumya2223/node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
